# Generated by Django 5.1.5 on 2025-01-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caregiverrelationship',
            unique_together={('user', 'caregiver')},
        ),
    ]
