# Generated by Django 5.1.5 on 2025-01-25 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_notificationpreference_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name': 'Notification Preference', 'verbose_name_plural': 'Notification Preferences'},
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='email',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='push',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='sms',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='notification_methods',
            field=models.JSONField(default=dict, help_text='Stores notification preferences as a JSON object'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
