# Generated by Django 5.1.5 on 2025-01-25 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_notificationpreference_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caregiverrelationship',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='caregiverrelationship',
            name='can_modify_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregiverrelationship',
            name='can_view_adherence',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caregiverrelationship',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caregiverrelationship',
            name='emergency_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caregiverrelationship',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caregiverrelationship',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='caregiverrelationship',
            name='permission_level',
            field=models.CharField(choices=[('VIEW', 'View Only'), ('MANAGE', 'Manage Medications'), ('FULL', 'Full Access')], default='VIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='caregiverrelationship',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caregiverrelationship',
            name='relationship',
            field=models.CharField(choices=[('FAMILY', 'Family Member'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('CARETAKER', 'Professional Caretaker'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='caregiverrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_relationships', to=settings.AUTH_USER_MODEL),
        ),
    ]
