# Generated by Django 5.1.5 on 2025-01-27 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='timing',
            field=models.CharField(choices=[('BEFORE_MEAL', 'Before Meal'), ('AFTER_MEAL', 'After Meal'), ('WITH_MEAL', 'With Meal'), ('ANY_TIME', 'Any Time')], default='ANY_TIME', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('AS_NEEDED', 'As Needed')], max_length=50),
        ),
    ]
