# Generated by Django 5.1.5 on 2025-01-20 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='AdherenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Not Taken', max_length=20)),
                ('reminder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedules.reminder')),
            ],
        ),
    ]
