# Generated by Django 5.1.5 on 2025-01-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_notificationpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationPreference',
        ),
    ]
