# Generated by Django 5.1.5 on 2025-01-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_delete_notificationpreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-sent_time']},
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_retry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adherencerecord',
            name='status',
            field=models.CharField(choices=[('NOT_TAKEN', 'Not Taken'), ('TAKEN', 'Taken'), ('SKIPPED', 'Skipped'), ('DELAYED', 'Delayed')], default='NOT_TAKEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
